meta_product_name: "FoodClass."
meta_title: "FoodClass. - Apprenez à cuisiner"
meta_description: "Apprenez à cuisiner en direct avec les Chefs"
meta_image: "cover-fb.jpeg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Card
